changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feat
        - feature
    - title: Bug fixes 🐛
      labels:
        - fix
    - title: Other Changes
      labels:
        - '*'
