kind: pipeline
name: CI - Build

steps:
  - name: CI - Build
    image: node:20-alpine
    environment:
      TURBO_TOKEN:
        from_secret: TURBO_TOKEN
      TURBO_TEAM:
        from_secret: TURBO_TEAM
    commands:
      - npm ci --legacy-peer-deps
      - npm run build
    when:
      branch:
        - development
        - staging
        - main

  # - name: If failure notification
  #   image: lesanpi/lark-plugin:send-message-v1
  #   environment:
  #     APP_ID:
  #       from_secret: LARK_APP_ID
  #     APP_SECRET:
  #       from_secret: LARK_APP_SECRET
  #     RECEIVE_ID:
  #       from_secret: LARK_CHAT_ID
  #     RECEIVE_ID_TYPE: 'chat_id'
  #     CONTENT: '{\"text\": \"<b>❌🔧 Build failure for MEIT </b>\\\n review at [Drone](https://drone.avilatek.com/Avila-Tek/meit) \"}'
  #     MSG_TYPE: text
  #   when:
  #     status:
  #       - failure
  #     branch:
  #       - development
  #       - staging
  #       - main

trigger:
  event:
    - pull_request
