import type { Metadata } from 'next';
import localFont from 'next/font/local';
// import '../css/color-variables.css';
import './globals.css';
// import '../css/bg-variables.css';
// import '../css/border-variables.css';
// import '../css/text-variables.css';
// import '../css/fg-variables.css';

import { ApolloWrapper } from '@/lib/graphql/apollo-wrapper';
import { ThemeProvider } from 'next-themes';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <ApolloWrapper>{children}</ApolloWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
