kind: pipeline
name: CI - Build

steps:
  - name: CI - Build
    image: node:22-alpine
    environment:
      TURBO_TOKEN:
        from_secret: TURBO_TOKEN
      TURBO_TEAM:
        from_secret: TURBO_TEAM
    commands:
      - npm ci --legacy-peer-deps
      - npm run build
    when:
      branch:
        - development
        - staging
        - main
trigger:
  event:
    - pull_request
