import { Inject, Injectable } from '@nestjs/common';
import { type IStructuredLogger, LOGGER_PORT } from '@zoom/utils';

@Injectable()
export class DomainToHttpMapper {
	constructor(
		@Inject(LOGGER_PORT)
		private readonly logger: IStructuredLogger,
	) {}

	private static readonly STATUS: Record<string, number> = {
		PROFILES_BUSINESS_PROFILE_NOT_FOUND: 404,
		PROFILES_GET_MEMBER_PERMISSIONS_FORBIDDEN: 403,
		PROFILES_ADDRESS_COUNTRY_ID_MISSING: 422,
		PROFILES_BUSINESS_ACCOUNT_DOCUMENT_IMMUTABLE: 422,
		PROFILES_INVALID_UNIT_OF_MEASURE: 422,
		PROFILES_BUSINESS_ACCOUNT_FORBIDDEN: 403,
		PROFILES_BUSINESS_ACCOUNT_NOT_FOUND: 404,
		PROFILES_BUSINESS_IDENTITY_CONFLICT: 409,
		PROFILES_CITY_LEGACY_ID_MISSING: 500,
		PROFILES_DEFAULT_DIMENSION_UNIT_NOT_FOUND: 500,
		PROFILES_DEFAULT_RETURN_TYPE_NOT_FOUND: 500,
		PROFILES_DEFAULT_WEIGHT_UNIT_NOT_FOUND: 500,
		PROFILES_DOCUMENT_TYPE_NOT_FOUND: 422,
		PROFILES_OWNER_ALREADY_EXISTS: 409,
		PROFILES_PHONE_PREFIX_NOT_FOUND: 422,
		MEMBERS_COLLABORATOR_INACTIVE: 422,
		MEMBERS_AT_LEAST_ONE_SERVICE_REQUIRED: 422,
		COLLABORATOR_INACTIVE: 422,
		PROFILES_RETURN_PREFERENCE_NOT_FOUND: 404,
		PROFILES_RETURN_TYPE_NOT_FOUND: 422,
		PROFILES_RETURN_TO_REQUIRED: 422,
		PROFILES_RETURN_TO_NOT_ALLOWED: 422,
		PROFILES_RETURN_OFFICE_NOT_ALLOWED: 422,
		PROFILES_RETURN_OFFICE_REQUIRED: 422,
		PROFILES_RETURN_OFFICE_NOT_FOUND: 422,
		PROFILES_BILLING_ADDRESS_NOT_FOUND: 422,
		PROFILES_RETURN_TYPE_NOT_SUPPORTED: 422,
		MEMBERS_OWNER_ONLY: 403,
		MEMBERS_NOT_FOUND: 404,
		MEMBERS_INVALID_STATUS: 422,
		MEMBERS_PROFILE_NOT_FOUND: 404,
		INVITATIONS_AT_LEAST_ONE_SERVICE_REQUIRED: 422,
		INVITATIONS_INVALID_PERMISSION_KEY: 422,
		INVITATIONS_OWNER_ONLY: 403,
		INVITATIONS_DUPLICATE_PENDING: 409,
		INVITATIONS_EMAIL_ALREADY_MEMBER: 409,
		INVITATIONS_ROLE_TEMPLATE_NOT_FOUND: 404,
		INVITATION_NOT_FOUND: 404,
		INVITATION_NOT_PENDING: 409,
		INVITATION_EMAIL_MISMATCH: 403,
		ROLE_TEMPLATES_NOT_FOUND: 404,
		RECIPIENTS_ADDRESS_NOT_SUPPORTED: 422,
		RECIPIENTS_LOCKER_INVALID: 422,
		RECIPIENTS_DEFAULT_COUNTRY_MISSING: 500,
		RECIPIENTS_NOT_FOUND: 404,
		RECIPIENTS_PROFILE_NOT_FOUND: 404,
		REGION_COUNTRY_NOT_FOUND: 422,
		REGION_MUNICIPALITY_NOT_FOUND: 422,
		REGION_PARISH_NOT_FOUND: 422,
		REGION_POSTAL_CODE_NOT_FOUND: 422,
		REGION_STATE_NOT_FOUND: 422,
		USERS_ACCOUNT_DATA_INCONSISTENT: 500,
		USERS_PROFILE_DETAIL_LOAD_ERROR: 500,
		USERS_PROFILE_NOT_FOUND: 404,
		USERS_PROFILE_SUSPENDED: 403,
		USERS_PROFILE_UNEXPECTED_ROLE: 500,
		PRICING_LOCKER_INVALID: 422,
		PRICING_WEIGHT_EXCEEDS_LIMIT: 422,
		PRICING_DECLARED_VALUE_OUT_OF_RANGE: 422,
		PRICING_HOME_DELIVERY_NOT_AVAILABLE: 422,
		PRICING_COD_NOT_AVAILABLE: 422,
		PRICING_ROUTE_NOT_FOUND: 422,
		PRICING_BASE_RATE_NOT_FOUND: 422,
		PRICING_ORIGIN_CITY_NOT_CONFIGURED: 422,
		PRICING_CALCULATION_FAILED: 500,
		PRICING_BCV_RATE_MISSING: 500,
	};

	map(errorCode: string): number {
		const status = DomainToHttpMapper.STATUS[errorCode];
		if (status === undefined) {
			this.logger.warn(
				{ event: 'http.mapper.unmapped_error', errorCode },
				`Unmapped domain error code "${errorCode}" — defaulting to 500`,
			);
			return 500;
		}
		return status;
	}
}
