name: Create release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.ref_name }}
      LINK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
      RECEIVE_ID_TYPE: 'email'
      RECEIVE_ID: 'lsanchez@avilatek.dev'
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
      - name: New release
        runs-on: ubuntu-22.04 # Or another suitable runner
        container: lesanpi/lark-release-version-card
