name: Create release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
      - name: New release notification
        env:
          POSTMARK_SERVER_TOKEN: ${{ secrets.POSTMARK_SERVER_TOKEN }}
          APP_NAME: Fullstack Template
          VERSION: ${{ github.ref_name }}
          RECEIVE_EMAIL: lsanchez@avilatek.dev
          LINK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
        uses: docker://lesanpi/email-deploy:v1.0.0
        # with:
        #   args: 'comando1 arg1 comando2 arg2'

        # runs-on: ubuntu-latest
        # container:
        #   image: lesanpi/lark-release-version-card
        #   env:
        #     VERSION: ${{ github.ref_name }}
        #     LINK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
        #     RECEIVE_ID_TYPE: 'email'
        #     RECEIVE_ID: 'lsanchez@avilatek.dev'
